### ISSUE TITLE
Example in README not running for me

### ISSUE THREAD

**Issue by seth127** [ntbloom/gamewinner#10]
I think we have some outdated code examples in our docs. I couldn't get [this README example](https://github.com/ntbloom/gamewinner/blob/473df453df6c9ff5e72507de12cb097b211d78e3/README.md?plain=1#L99-L104) to run:

```
$ python
Python 3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gamewinner import gamewinner
>>> from gamewinner.strategies.evanmiya.slothfire_steady import SlothfireSteady
>>> gamewinner.play(SlothfireSteady())
>>> gamewinner.play(year = 2023, strategy = SlothfireSteady())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: play() missing 2 required positional arguments: 'west_final_four_matchup' and 'printer'
```

_This code_ ran for me:

```python
from gamewinner import gamewinner
from gamewinner.strategies.evanmiya.slothfire_steady import SlothfireSteady
import gamewinner.printers as printers
from gamewinner.team import GeographicRegion

gamewinner.play(
    year = 2023, 
    strategy = SlothfireSteady(),
    west_final_four_matchup = GeographicRegion.MIDWEST,
    printer = printers.WithColors
)
```

... but that's kind of a mouthful. I think we probably want to make some of those default args. Or advertise a different entry point in the README. For example, [this](https://github.com/ntbloom/gamewinner/pull/7/commits/8e6f7916212672282b2d0c6a2003fd5f8d95510d) worked like a charm.

**Comment by seth127** [comment]
It would probably be nice to put some working examples in there too. Something like 

------

```
$ poetry run play --strategy VanillaMiya
```

and/or

```python
from gamewinner import gamewinner
from gamewinner.strategies.evanmiya.vanilla_miya import VanillaMiya

gamewinner.play(strategy = VanillaMiya())
```

**Comment by ntbloom** [comment]
Should be handled by 2ebbea3edf837221763a5e651e624ef15ec20c29.  Let me know if this didn't take care of everything.
